"""Make brand_id and category_id nullable

Revision ID: 1793a2b8523d
Revises: 488350b719ed
Create Date: 2026-01-24 13:37:56.891282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1793a2b8523d'
down_revision: Union[str, None] = '488350b719ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'brand_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('products', 'category_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('products', 'brand_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
