"""add_password_hash_and_recommendation_columns

Revision ID: 488350b719ed
Revises: de571193d02e
Create Date: 2026-01-20 13:14:21.316722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488350b719ed'
down_revision: Union[str, None] = 'de571193d02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('recommendation_text', sa.String(length=2000), nullable=True))
    op.add_column('products', sa.Column('recommendation_generated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('products', 'recommendation_generated_at')
    op.drop_column('products', 'recommendation_text')
    # ### end Alembic commands ###
