"""add weekly_rankings table

Revision ID: 6beb10e05c8c
Revises: 7d35e126d195
Create Date: 2026-01-25 11:16:41.383151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6beb10e05c8c'
down_revision: Union[str, None] = '7d35e126d195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_rankings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('watchlist_count', sa.Integer(), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('ai_generated_at', sa.DateTime(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'year', 'week_number', name='uq_product_year_week')
    )
    op.create_index('idx_product_year_week', 'weekly_rankings', ['product_id', 'year', 'week_number'], unique=False)
    op.create_index('idx_year_week', 'weekly_rankings', ['year', 'week_number'], unique=False)
    op.create_index(op.f('ix_weekly_rankings_product_id'), 'weekly_rankings', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_rankings_product_id'), table_name='weekly_rankings')
    op.drop_index('idx_year_week', table_name='weekly_rankings')
    op.drop_index('idx_product_year_week', table_name='weekly_rankings')
    op.drop_table('weekly_rankings')
    # ### end Alembic commands ###
