"""make brand_id category_id checked_at nullable

Revision ID: c18730160b0c
Revises: 488350b719ed
Create Date: 2026-01-24 14:15:21.607606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c18730160b0c'
down_revision: Union[str, None] = '488350b719ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'checked_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'checked_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
